#!/bin/sh
#
# $NetBSD: cleartmp,v 1.11 2012/10/24 21:23:55 apb Exp $
#

# PROVIDE: cleartmp
# REQUIRE: mountall
# BEFORE:  DAEMON

$_rc_subr_loaded . /etc/rc.subr

name="cleartmp"
rcvar="clear_tmp"
start_cmd="cleartmp_start"
stop_cmd=":"

cleartmp_start()
{
	echo "Clearing temporary files."
	if checkyesno per_user_tmp && [ -d ${per_user_tmp_dir} ]; then
		tmp_dir=${per_user_tmp_dir}
	else
		tmp_dir="/tmp"
		# Check if /tmp was created by the perusertmp rc.d
		# script and recreate it if necessary.
		if [ "$(/usr/bin/readlink /tmp)" = ${per_user_tmp_dir}/@ruid ]; then
			/bin/rm -rf ${tmp_dir}
			/bin/mkdir ${tmp_dir}
			/usr/sbin/chown root:wheel ${tmp_dir}
			/bin/chmod 1777 ${tmp_dir}
		fi
	fi

	#
	#	Delete almost everything, except lost+found, quota.user,
	#	and quota.group in the top level.  (This is not needed
	#	with mfs or tmpfs /tmp, but doesn't hurt anything).
	#
	#	The find command, with "-exec ... +" instead of "-exec
	#	... \;", will pass many file or dir names to each
	#	invocation of "rm -rf".  We avoid using any glob
	#	patterns because of the risk of "Arg list too long"
	#	errors when there are very many files.
	#
	(cd ${tmp_dir} &&
	    find -x . ! -name . ! -name lost+found ! -name quota.user \
		! -name quota.group -exec rm -rf -- {} \+ -type d -prune)

	if checkyesno per_user_tmp && [ -d ${per_user_tmp_dir} ]; then
		# Create user tmp directory.
		if [ ! -d ${per_user_tmp_dir}/0 ]; then
			/bin/mkdir ${per_user_tmp_dir}/0
			/usr/sbin/chown root:wheel ${per_user_tmp_dir}/0
			/bin/chmod 1700 ${per_user_tmp_dir}/0
		fi
		if [ -n "${per_user_tmp_prepare_users}" ]; then
			for user in ${per_user_tmp_prepare_users}; do
				uid=$(/usr/bin/id -u ${user})
				if [ $? -eq 0 ] && [ ! -d ${per_user_tmp_dir}/${uid} ]; then
					/bin/mkdir ${per_user_tmp_dir}/${uid}
					/usr/sbin/chown ${user}:$(/usr/bin/id -gn ${user}) ${per_user_tmp_dir}/${uid}
					/bin/chmod 1700 ${per_user_tmp_dir}/${uid}
				fi
			done
		fi
	fi
}

load_rc_config $name
run_rc_command "$1"
