#!/bin/sh
#
# $NetBSD: perusertmp,v 1.7 2007/12/04 22:09:01 mjf Exp $
#

# PROVIDE: perusertmp
# REQUIRE: mountall
# BEFORE:  cleartmp
# KEYWORD: shutdown

$_rc_subr_loaded . /etc/rc.subr

name="perusertmp"
rcvar="per_user_tmp"
start_cmd="perusertmp_start"
stop_cmd="perusertmp_stop"

perusertmp_start()
{
	echo "Preparing per-user /tmp."

	# If /tmp is a mount point, we can't do anything.
	if [ -d "/tmp" ]; then
		local mount_point

		mount_point=$(cd /tmp && /bin/df . | /usr/bin/tail -1 | /usr/bin/awk '{print $6}')
		if [ "${mount_point}" = "/tmp" ]; then
			echo "WARNING: /tmp is mounted."
			exit 1
		fi
	fi

	# Enable magic symlinks.
	/sbin/sysctl -qw vfs.generic.magiclinks=1

	# Fixup real temporary directory.
	if [ ! -d ${per_user_tmp_dir} ]; then
		/bin/mkdir -p ${per_user_tmp_dir}
	fi
	/usr/sbin/chown root:wheel ${per_user_tmp_dir}
	/bin/chmod 0555 ${per_user_tmp_dir}

	# Create magic link for /tmp.
	if [ "$(/usr/bin/readlink /tmp)" != ${per_user_tmp_dir}/@ruid ]; then
		/bin/rm -rf /tmp
		/bin/ln -s ${per_user_tmp_dir}/@ruid /tmp
	fi

	if ! checkyesno clear_tmp; then
		# Create user tmp directory.
		if [ ! -d ${per_user_tmp_dir}/0 ]; then
			/bin/mkdir ${per_user_tmp_dir}/0
			/usr/sbin/chown root:wheel ${per_user_tmp_dir}/0
			/bin/chmod 1700 ${per_user_tmp_dir}/0
		fi
		if [ -n "${per_user_tmp_prepare_users}" ]; then
			for user in ${per_user_tmp_prepare_users}; do
				uid=$(/usr/bin/id -u ${user})
				if [ $? -eq 0 ] && [ ! -d ${per_user_tmp_dir}/${uid} ]; then
					/bin/mkdir ${per_user_tmp_dir}/${uid}
					/usr/sbin/chown ${user}:$(/usr/bin/id -gn ${user}) ${per_user_tmp_dir}/${uid}
					/bin/chmod 1700 ${per_user_tmp_dir}/${uid}
				fi
			done
		fi
	fi
}

perusertmp_stop()
{
	if [ -d "${per_user_tmp_dir}" ]; then
		mount_point=$(cd ${per_user_tmp_dir} && /bin/df . | /usr/bin/tail -1 | /usr/bin/awk '{print $6}')
		mount_fs=$(cd ${per_user_tmp_dir} && /bin/df . | /usr/bin/tail -1 | /usr/bin/awk '{print $1}')
		if [ "${mount_point}" = "${per_user_tmp_dir}" ] && ( [ "${mount_fs}" = "tmpfs" ] || [ ${mount_fs} = "mfs" ] ); then
			if [ "$(/usr/bin/readlink /tmp)" = ${per_user_tmp_dir}/@ruid ]; then
				/bin/rm -f /tmp
				/bin/mkdir /tmp
				/usr/sbin/chown root:wheel /tmp
				/bin/chmod 1777 /tmp
			fi
		fi
	fi
}

load_rc_config $name
run_rc_command "$1"
